#!/bin/sh
#
# l0c pre-commit hook for quality-checking the commit.
#
# This hook checks the following:
#
#   * Trailing whitespace.
#   * Runs hlint.
#   * Tries to compile l0c.
#
# It also yells at you to run the test suite, although it doesn't do
# it by itself.

initial=c508f9f531929f6bed868243334417ef6c840cb4 # Hash of initial commit.

fail() {
    echo "Aborting commit due to verification errors."
    echo "If you disagree, use git commit --no-verify."
    exit 1
}

echo Quality-checking commit...
echo

# Find files with trailing whitespace
if git diff-index --check HEAD | egrep -v '^[+-]'; then
    fail
fi

# Run hlint on changed files.
for file in $(git diff-index --name-only HEAD | egrep '\.l?hsc?$'); do
    if [ $file != src/L0/CCodeGen.hs ]; then # This one cannot be parsed by hlint.
        if ! hlint -i "Reduce duplication" "$file"; then
            fail
        fi
    fi
done

if ! cabal build; then
    fail
fi
