name: 'Benchmark'
description: 'Run benchmark suite'
inputs:
  backend:
    description: 'Backend to use'
    required: true
  system:
    description: 'Name of system (e.g. GPU name)'
    required: true
  options:
    description: 'Options to pass to futhark bench'
    required: false
    default: ''
  slurm:
    description: 'Options to pass to srun'
    required: false
    default: ''
  gpu:
    description: 'The GPU and numbers of GPUs to use'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/benchmark/is-slurm
      id: slurm

    - uses: ./.github/actions/benchmark/default
      if: steps.slurm.outputs.is-slurm == 'false'
      with:
        backend: ${{inputs.backend}}
        options: ${{inputs.options}}
        system: ${{inputs.system}}

    - uses: ./.github/actions/benchmark/slurm
      if: steps.slurm.outputs.is-slurm == 'true'
      with:
        backend: ${{inputs.backend}}
        system: ${{inputs.system}}
        options: ${{inputs.options}}
        slurm: ${{inputs.slurm}}
        gpu: ${{inputs.gpu}}
