name: 'Slurm Benchmark'
description: 'Run benchmark suite'
inputs:
  backend:
    description: 'Backend to use'
    required: true
  system:
    description: 'Name of system (e.g. GPU name)'
    required: true
  options:
    description: 'Options to pass to futhark bench'
    required: false
    default: ''
  slurm:
    description: 'Options to pass to srun'
    required: false
    default: ''
  gpu:
    description: 'The GPU and numbers of GPUs to use'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: futhark-nightly-linux-x86_64.tar.xz
    - name: Setup compiler
      shell: bash
      run: |
        tar xvf futhark-nightly-linux-x86_64.tar.xz
    - name: Save slurmbench.py
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/diku-dk/futhark-ci/slurm/slurmbench.py > slurmbench.py
    - name: Run benchmarks
      shell: bash
      run: |
        python3.9 slurmbench.py --gpu=${{inputs.gpu}} --futhark="$PWD/futhark-nightly-linux-x86_64/bin/futhark" --slurm-options=${{inputs.slurm}} --futhark-options='--ignore-files /lib/ --backend=${{inputs.backend}} --exclude no_${{inputs.system}} ${{inputs.options}}' --json=futhark-${{inputs.backend}}-${{inputs.system}}-$GITHUB_SHA.json --benchmarks=futhark-benchmarks
    - uses: actions/upload-artifact@v1
      with:
        name: futhark-${{inputs.backend}}-${{inputs.system}}-${{ github.sha }}.json
        path: futhark-${{inputs.backend}}-${{inputs.system}}-${{ github.sha }}.json
