- modules:
  - {name: [Data.Set, Data.HashSet], as: S}
  - {name: [Data.Map, Data.Map.*], as: M}
  - {name: [Data.List.NonEmpty], as: NE}
  - {name: [Data.List], as: L}

- error: {lhs: map subExpRes, rhs: subExpsRes}
- error: {lhs: map varRes, rhs: varsRes}
- error: {lhs: return, rhs: pure}
- error: {lhs: nameIn x y, rhs: x `nameIn` y, side: not (isInfixApp original) && not (isParen result), name: Use infix}
- error: {lhs: not (x `nameIn` y), rhs: x `notNameIn` y}
- error: {lhs: not (any (`nameIn` x) y), rhs: all (`notNameIn` x) y}
- error: {lhs: Data.Text.pack (show x), rhs: Futhark.Util.showText x}
- error: {lhs: Data.List.nub, rhs: Futhark.Util.nubOrd}
- error: {lhs: "copyDWIM p [] y [DimFix i]", rhs: "copyDWIMFix p [] y [i]" }
- error: {lhs: "copyDWIM x [DimFix i] y []", rhs: "copyDWIMFix x [i] y []" }
- error: {lhs: "copyDWIM x [DimFix i] y [DimFix j]", rhs: "copyDWIMFix x [i] y [j]" }
