name: futhark
version: "0.7.0"
synopsis: An optimising compiler for a functional, array-oriented language.
description: See the website at https://futhark-lang.org
homepage: https://futhark-lang.org
maintainer: Troels Henriksen athas@sigkill.dk
license: ISC
github: diku-dk/futhark
category: Language

ghc-options: -Wall -Wcompat -Wredundant-constraints -Wincomplete-record-updates

extra-source-files:
  - rts/python/*.py
  - rts/c/*.h
  - rts/csharp/*.cs

  - futlib/*.fut

dependencies:
  - base >= 4 && < 5
  - array >= 0.4
  - binary >= 0.8.3
  - data-binary-ieee754 >= 0.1
  - vector >= 0.12
  - vector-binary-instances
  - containers >= 0.5
  - mtl >= 2.2.1
  - transformers >= 0.3
  - srcloc >= 0.4
  - language-c-quote >= 0.12
  - mainland-pretty >= 0.6.1
  - megaparsec >= 6.0.2
  - regex-tdfa >= 1.2
  - filepath >= 1.4.1.1
  - dlist >= 0.6.0.1
  - bytestring >= 0.10.8
  - text >= 1.2.2.2
  - raw-strings-qq >= 1.1
  - neat-interpolation >= 0.3
  - file-embed >= 0.0.9
  - directory >= 1.3.0.0
  - directory-tree >= 0.12.1
  - gitrev >= 1.2.0
  - parallel >= 3.2.1.0
  - bifunctors >= 5.4.2
  - blaze-html >= 0.9.0.1
  - template-haskell >= 2.11.1
  - th-lift-instances >= 0.1.11
  - extra >= 1.5.3
  - process >= 1.4.3.0
  - markdown >= 0.1.16
  - zlib >= 0.6.1.2
  - versions >= 3.3.2
  - http-client >= 0.5.7.0
  - http-client-tls >= 0.3.5.1
  - http-conduit >= 2.2.4
  - process-extras >= 0.7.2
  - free >= 4.12.4
  - zip-archive >= 0.3.1.1
  - time >= 1.6.0.1

when:
- condition: "!impl(ghc >= 8.0)"
  dependencies: semigroups == 0.18.*

library:
  build-tools:
    - alex
    - happy

  source-dirs: src

  other-modules:
    - Language.Futhark.Parser.Parser
    - Language.Futhark.Parser.Lexer
    - Paths_futhark

executables:
  futhark: &futhark
    main: src/futhark.hs
    dependencies:
      - futhark
      - random
      - temporary
      - json
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -qg"
  futharki:
    <<: *futhark
    dependencies:
      - futhark
      - haskeline
    main: src/futharki.hs
  futhark-c:
    <<: *futhark
    main: src/futhark-c.hs
  futhark-opencl:
    <<: *futhark
    main: src/futhark-opencl.hs
  futhark-py:
    <<: *futhark
    main: src/futhark-py.hs
  futhark-pyopencl:
    <<: *futhark
    main: src/futhark-pyopencl.hs
  futhark-cs:
    <<: *futhark
    main: src/futhark-cs.hs
  futhark-csopencl:
    <<: *futhark
    main: src/futhark-csopencl.hs
  futhark-test:
    <<: *futhark
    main: src/futhark-test.hs
  futhark-bench:
    <<: *futhark
    main: src/futhark-bench.hs
  futhark-dataset:
    <<: *futhark
    main: src/futhark-dataset.hs
  futhark-doc:
    <<: *futhark
    main: src/futhark-doc.hs
  futhark-pkg:
    <<: *futhark
    main: src/futhark-pkg.hs

tests:
  unit:
    source-dirs: unittests
    main: futhark_tests.hs
    dependencies:
      - QuickCheck >= 2.8
      - tasty
      - tasty-quickcheck
      - HUnit
      - tasty-hunit
      - futhark
