name: futhark
version: "0.13.0"
synopsis: An optimising compiler for a functional, array-oriented language.
description: |
  Futhark is a small programming language designed to be compiled to
  efficient parallel code. It is a statically typed, data-parallel,
  and purely functional array language in the ML family, and comes
  with a heavily optimising ahead-of-time compiler that presently
  generates GPU code via CUDA and OpenCL, although the language itself
  is hardware-agnostic.

  For more information, see the website at https://futhark-lang.org
homepage: https://futhark-lang.org
maintainer: Troels Henriksen athas@sigkill.dk
license: ISC
github: diku-dk/futhark
category: Language

ghc-options: -Wall -Wcompat -Wredundant-constraints -Wincomplete-record-updates -Wmissing-export-lists

extra-source-files:
  - rts/python/*.py
  - rts/c/*.h
  - rts/csharp/*.cs
  - rts/futhark-doc/*.css

  - futlib/*.fut

  - docs/Makefile
  - docs/conf.py
  - docs/index.rst
  - docs/man/*.rst
  - package.yaml

library:
  dependencies:
    - base >= 4.13 && < 5
    - array >= 0.4
    - binary >= 0.8.3
    - data-binary-ieee754 >= 0.1
    - vector >= 0.12
    - vector-binary-instances >= 0.2.2.0
    - containers >= 0.6.2.1
    - mtl >= 2.2.1
    - transformers >= 0.3
    - srcloc >= 0.4
    - language-c-quote >= 0.12
    - mainland-pretty >= 0.6.1
    - megaparsec >= 7.0.1
    - parser-combinators >= 1.0.0
    - regex-tdfa >= 1.2
    - filepath >= 1.4.1.1
    - dlist >= 0.6.0.1
    - bytestring >= 0.10.8
    - text >= 1.2.2.2
    - neat-interpolation >= 0.3
    - file-embed >= 0.0.9
    - directory >= 1.3.0.0
    - directory-tree >= 0.12.1
    - gitrev >= 1.2.0
    - parallel >= 3.2.1.0
    - blaze-html >= 0.9.0.1
    - template-haskell >= 2.11.1
    - process >= 1.4.3.0
    - markdown >= 0.1.16
    - zlib >= 0.6.1.2
    - versions >= 3.3.1
    - http-client >= 0.5.7.0
    - http-client-tls >= 0.3.5.1
    - http-conduit >= 2.2.4
    - process-extras >= 0.7.2
    - free >= 4.12.4
    - zip-archive >= 0.3.1.1
    - time >= 1.6.0.1
    - ansi-terminal >= 0.6.3.1
    - random
    - temporary
    - aeson >= 1.0.0.0
    - haskeline
    - utf8-string >= 1
    - terminal-size >= 0.3
    - unordered-containers >= 0.2.7

  build-tools:
    - alex
    - happy

  source-dirs: src

  other-modules:
    - Language.Futhark.Parser.Parser
    - Language.Futhark.Parser.Lexer
    - Paths_futhark

executables:
  futhark: &futhark
    main: src/futhark.hs
    dependencies:
      - base
      - futhark
      - text
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -qg"

tests:
  unit:
    source-dirs: unittests
    main: futhark_tests.hs
    dependencies:
      - base
      - futhark
      - containers
      - mtl
      - text
      - QuickCheck >= 2.8
      - tasty
      - tasty-quickcheck
      - tasty-hunit
      - megaparsec
      - parser-combinators
