resolver: nightly-2021-06-19
packages:
- .

flags: {}

extra-package-dbs: []

nix:
    packages: [zlib.dev, zlib.out, pkgconfig]

# By default, stack doesn't compile multiple modules in parallel.
# This makes it do so.
ghc-options:
  $locals: -j -optP-Wno-nonportable-include-path

extra-deps:
- futhark-data-1.0.2.0
- futhark-server-1.1.2.0
- githash-0.1.6.1@sha256:a81001a9766438b3384d8f56584235f21c285889c6d4084f98dee8260010e0ac,1527
- aeson-2.0.1.0
