resolver: nightly-2021-06-19
packages:
- .

flags: {}

extra-package-dbs: []

nix:
    packages: [zlib.dev, zlib.out, pkgconfig]

# By default, stack doesn't compile multiple modules in parallel.
# This makes it do so.
ghc-options:
  $locals: -j -optP-Wno-nonportable-include-path

extra-deps:
- futhark-data-1.0.1.1
- futhark-server-1.1.0.0
