resolver: nightly-2021-04-19
packages:
- .

extra-deps: []

flags: {}

extra-package-dbs: []

nix:
    packages: [zlib.dev, zlib.out, pkgconfig]

# By default, stack doesn't compile multiple modules in parallel.
# This makes it do so.
ghc-options:
  $locals: -j -optP-Wno-nonportable-include-path

extra-deps:
- versions-5.0.0
