resolver: nightly-2022-01-14
packages:
- .

flags: {}

extra-package-dbs: []

nix:
    packages: [zlib.dev, zlib.out, pkgconfig]

# By default, stack doesn't compile multiple modules in parallel.
# This makes it do so.
ghc-options:
  $locals: -j -optP-Wno-nonportable-include-path

extra-deps:
- futhark-data-1.0.3.0
- futhark-server-1.1.2.1
- futhark-manifest-1.0.0.0
- aeson-2.0.1.0
