-- Polymorphic infix operators ought to work, even in sections.
-- ==
-- input { [[1],[2],[3]] [[4],[5],[6]] [[true]] [[false]] }
-- output { [[1],[2],[3]] [[true]]
--          [[1],[2],[3]] [[true]] }
