-- Reads can be delayed into kernel bodies and combining operators.
-- ==
-- structure gpu {
--   /Index 0
--   /SegScan 1
--   /SegMap 0
-- }
-- This read can be delayed into op
-- This read can be delayed into the kernel body
