-- Array reads are sunk to their deepest possible branch.
-- ==
-- structure gpu {
--   GPUBody 1
--   /Loop/Index 0
--   /Loop/If/True/GPUBody 1
--   /Loop/If/True/Index 1
-- }
-- This function can only be run on host and thus requires
-- its argument to be made available there.
-- reads of y and z should be sunk here
