-- Array reads are sunk to their deepest possible branch.
-- ==
-- structure gpu {
--   GPUBody 1
--   /Index 0
--   /If/True/Index 1
--   /If/True/GPUBody/Index 1
--   /If/True/GPUBody/If/True/Index 1
--   /If/True/GPUBody/If/False/Index 1
-- }
