#!/usr/bin/env python3

import g
import numpy as np

obj = g.g()

n = 1
m = 1000

vec_n = obj.mk_vec(n)
vec_m = obj.mk_vec(m)

assert(obj.use_vec(vec_n, vec_n) == 0)

try:
    obj.use_vec(vec_n, vec_m) # Should fail.
    assert(False)
except Exception as e:
    assert('invalid' in str(e))
