-- testing that variable shadowing and chunking
-- doesn't allow for duplicate definitions
-- ==
-- error: Duplicate
-- the type is defined from l. 1
-- type is defined from l.5
-- is defined at l. 5
-- REDEFINITION OF foo IN Struct M1
-- defined at line 17
-- is defined at l. 13
