#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/../../../futhark/" # Makes assumption.

compiler="$1"
if ! [ "$compiler" ]; then
    compiler=futhark-c
fi

do_all_combinations="$2"

ftest() {
    futhark-test --nobuffer -c --compiler=$compiler tests 2>&1
}

fproc() {
    grep -E '^tests/[^.]+\.fut:$' | sort
}

# Path assumptions.
without=$HOME/temp/futhark/futhark-mbm-failures-$compiler-without
with=$HOME/temp/futhark/futhark-mbm-failures-$compiler-with
if ! [ -f $without ]; then
    ftest > $without || true
fi
export IN_PLACE_LOWERING=0
if [ "$do_all_combinations" ]; then
    with=$HOME/temp/futhark/futhark-mbm-failures-$compiler-with-coalescing
    MEMORY_BLOCK_MERGING_COALESCING=1 ftest > $with || true
    echo $compiler coalescing
    comm -3 <(fproc < $without) <(fproc < $with)

    with=$HOME/temp/futhark/futhark-mbm-failures-$compiler-with-reuse
    MEMORY_BLOCK_MERGING_REUSE=1 ftest > $with || true
    echo $compiler reuse
    comm -3 <(fproc < $without) <(fproc < $with)

    with=$HOME/temp/futhark/futhark-mbm-failures-$compiler-with-both
    MEMORY_BLOCK_MERGING_COALESCING=1 MEMORY_BLOCK_MERGING_REUSE=1 ftest > $with || true
    echo $compiler both
    comm -3 <(fproc < $without) <(fproc < $with)
else
    export MEMORY_BLOCK_MERGING_COALESCING=1
    export MEMORY_BLOCK_MERGING_REUSE=1
    ftest > $with || true
    echo $compiler
    comm -3 <(fproc < $without) <(fproc < $with)
fi
